/*
 * Generated by dtrace(1M).
 */

#ifndef	_DTRACE_PROVIDER_H
#define	_DTRACE_PROVIDER_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define BOLERO_INSTRUMENT_STABILITY "___dtrace_stability$bolero_instrument$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define BOLERO_INSTRUMENT_TYPEDEFS "___dtrace_typedefs$bolero_instrument$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	BOLERO_INSTRUMENT_START() \
do { \
	__asm__ volatile(".reference " BOLERO_INSTRUMENT_TYPEDEFS); \
	__dtrace_probe$bolero_instrument$start$v1(); \
	__asm__ volatile(".reference " BOLERO_INSTRUMENT_STABILITY); \
} while (0)
#define	BOLERO_INSTRUMENT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$bolero_instrument$start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	BOLERO_INSTRUMENT_STOP() \
do { \
	__asm__ volatile(".reference " BOLERO_INSTRUMENT_TYPEDEFS); \
	__dtrace_probe$bolero_instrument$stop$v1(); \
	__asm__ volatile(".reference " BOLERO_INSTRUMENT_STABILITY); \
} while (0)
#define	BOLERO_INSTRUMENT_STOP_ENABLED() \
	({ int _r = __dtrace_isenabled$bolero_instrument$stop$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$bolero_instrument$start$v1(void);
extern int __dtrace_isenabled$bolero_instrument$start$v1(void);
extern void __dtrace_probe$bolero_instrument$stop$v1(void);
extern int __dtrace_isenabled$bolero_instrument$stop$v1(void);

#else

#define	BOLERO_INSTRUMENT_START() \
do { \
	} while (0)
#define	BOLERO_INSTRUMENT_START_ENABLED() (0)
#define	BOLERO_INSTRUMENT_STOP() \
do { \
	} while (0)
#define	BOLERO_INSTRUMENT_STOP_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _DTRACE_PROVIDER_H */
