[package]
name = "reduce"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["."]

[dependencies]

[dev-dependencies]
bolero = { path = "../../lib/bolero" }


[profile.fuzz]
inherits = "dev"
opt-level = 3
incremental = false
codegen-units = 1


